spring:
  application:
    name: unit-test-spring
  config:
    import: application_prod.yml
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:app.pub

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  port: 5000
  servlet:
    session:
      timeout: 20m