spring:
  config:
    activate:
      on-profile: prod
  application:
    name: unit-test-spring
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  port: 5000
  servlet:
    session:
      timeout: 60m
